import { defineCloudflareConfig } from "@opennextjs/cloudflare";
import r2IncrementalCache from "@opennextjs/cloudflare/overrides/incremental-cache/r2-incremental-cache";

/**
 * OpenNext Cloudflare Configuration
 * 
 * Generated by opennextjs-cli
 * 
 * Caching Strategy: r2
 * Next.js Version: 15.1.0
 * 
 * See: https://opennext.js.org/cloudflare
 */
export default defineCloudflareConfig({
  incrementalCache: r2IncrementalCache,
  enableCacheInterception: true,
});
