/**
 * 构建时预读翻译文件
 *
 * 读取 public/locales/ 所有 JSON，生成 src/i18n/locales-data.ts
 * 用于 Cloudflare Workers 环境（无文件系统访问）
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

try {
  const localesDir = "./public/locales";
  const result: Record<string, Record<string, unknown>> = {};

  for (const locale of readdirSync(localesDir)) {
    result[locale] = {};
    const nsDir = join(localesDir, locale);
    for (const file of readdirSync(nsDir)) {
      if (file.endsWith(".json")) {
        const ns = file.replace(".json", "");
        const content = readFileSync(join(nsDir, file), "utf-8");
        result[locale][ns] = JSON.parse(content);
      }
    }
  }

  // 生成 TypeScript 文件
  const output = `// Auto-generated by scripts/build-locales.ts
// Do not edit manually

export const localesData = ${JSON.stringify(result)} as Record<string, Record<string, Record<string, unknown>>>;
`;

  writeFileSync("./src/i18n/locales-data.ts", output);
  console.log("✅ locales-data.ts generated successfully");
} catch (err) {
  console.error("Failed to generate locales-data.ts:", (err as Error).message);
  process.exit(1);
}
