#!/usr/bin/env node
/**
 * Post-build patch script for OpenNext.js Cloudflare Workers
 * 
 * This script patches the generated worker.js and init.js files to:
 * - Add setImmediate polyfill at module level
 * - Handle Prisma WASM module (if Prisma is used)
 * 
 * Generated by opennextjs-cli
 * Next.js Version: 15.5.10
 * 
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { globSync } from 'glob';

const moduleLevelPolyfill = `// CRITICAL: Define setImmediate polyfill at module level before any imports
// This fixes the "Cannot assign to read only property 'setImmediate'" error
// Next.js's fast-set-immediate.external.js tries to patch setImmediate on a module object
// Must be defined before any Next.js code runs
if (typeof globalThis.setImmediate === 'undefined' || !Object.getOwnPropertyDescriptor(globalThis, 'setImmediate')?.writable) {
  const setImmediateImpl = (fn, ...args) => setTimeout(fn, 0, ...args);
  try {
    Object.defineProperty(globalThis, "setImmediate", {
      value: setImmediateImpl,
      writable: true,
      configurable: true,
      enumerable: false,
    });
  } catch (e) {
    try {
      globalThis.setImmediate = setImmediateImpl;
    } catch {
      // Silent fallback
    }
  }
}
if (typeof globalThis.clearImmediate === 'undefined') {
  Object.defineProperty(globalThis, "clearImmediate", {
    value: (id) => clearTimeout(id),
    writable: true,
    configurable: true,
    enumerable: false,
  });
}

`;

// Patch worker.js
const workerJsPath = join(process.cwd(), '.open-next/worker.js');
if (existsSync(workerJsPath)) {
  try {
    let workerContent = readFileSync(workerJsPath, 'utf-8');
    
    if (!workerContent.startsWith('// CRITICAL: Define setImmediate polyfill')) {
      workerContent = moduleLevelPolyfill + workerContent;
      writeFileSync(workerJsPath, workerContent, 'utf-8');
      console.log('✓ Added setImmediate polyfill to worker.js');
    } else {
      console.log('✓ setImmediate polyfill already exists in worker.js');
    }

    // Remove nodeTimers.setImmediate assignments from bundled code
    if (workerContent.includes('nodeTimers.setImmediate')) {
      workerContent = workerContent.replace(
        /globalThis\.setImmediate\s*=\s*nodeTimers\.setImmediate\s*=/g,
        'globalThis.setImmediate ='
      );
      workerContent = workerContent.replace(
        /nodeTimers\.setImmediate\s*=\s*/g,
        ''
      );
      workerContent = workerContent.replace(
        /globalThis\.clearImmediate\s*=\s*nodeTimers\.clearImmediate\s*=/g,
        'globalThis.clearImmediate ='
      );
      workerContent = workerContent.replace(
        /nodeTimers\.clearImmediate\s*=\s*/g,
        ''
      );
      writeFileSync(workerJsPath, workerContent, 'utf-8');
      console.log('✓ Removed nodeTimers assignments from bundled code');
    }
  } catch (error) {
    console.warn('⚠ Could not patch worker.js:', error?.message || String(error));
  }
} else {
  console.log('ℹ worker.js not found, skipping patch');
}

// Patch init.js
const initJsPath = join(process.cwd(), '.open-next/cloudflare/init.js');
if (existsSync(initJsPath)) {
  try {
    let content = readFileSync(initJsPath, 'utf-8');
    
    if (!content.startsWith('// CRITICAL: Define setImmediate polyfill')) {
      content = moduleLevelPolyfill + content;
      writeFileSync(initJsPath, content, 'utf-8');
      console.log('✓ Added setImmediate polyfill to init.js');
    } else {
      console.log('✓ setImmediate polyfill already exists in init.js');
    }
  } catch (error) {
    console.warn('⚠ Could not patch init.js:', error?.message || String(error));
  }
} else {
  console.log('ℹ init.js not found, skipping patch');
}

// Prisma WASM handling (if Prisma is detected)
// Note: This is a simplified version. Full Prisma support requires more complex patching.
const prismaClientPath = join(process.cwd(), 'node_modules/.prisma/client');
if (existsSync(prismaClientPath)) {
  console.log('ℹ Prisma detected. For full Prisma WASM support, see: https://opennext.js.org/cloudflare/troubleshooting');
}
